[package]
name = "xxd-rust"
version = "0.1.0"
edition = "2021"
author = "John Desmond"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.28"
hex = "0.4.3"
